spring.application.name=web2
server.port=8084

#CONEXÃO BANDO MariaDB
#Lembre-se de a cada inicialização, acessar Serviços - MariaDB - Iniciar
spring.datasource.url=jdbc:mariadb://localhost:3306/web2
spring.datasource.username=root
spring.datasource.password=leo135
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria/atualiza tabelas automaticamente
# spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
# spring.jpa.show-sql=true

# Habilita console web do H2
# spring.h2.console.enabled=true

# URL do console
# spring.h2.console.path=/h2-console

